version: "3.9"
   
services:
  backend:
    networks:
      default:
        aliases:
          - backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    networks:
      default:
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        API_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
networks:
  default: